#!/bin/bash

set -e

SCRIPTPATH=$(pwd -P)
cd "$SCRIPTPATH"

MAVEN_QUIET=""
SKIP_CHECKSTYLE=$TRAVIS
INTELLIJ_VERSION=false
BUILD_ECLIPSE=true
BUILD_INTELLIJ=true

while getopts "hqve:" option; do
  echo $option
    case $option in
        h) echo "usage: $0 [-h] [-q] [-v] [-e eclipse/intellij]"; exit ;;
        q) MAVEN_QUIET="-q" ;;
        v) INTELLIJ_VERSION=true ;;
        e)
          shopt -s nocasematch
          case $OPTARG in 
            eclipse) BUILD_ECLIPSE=false ;;
            intellij) BUILD_INTELLIJ=false ;;
          esac ;;
        ?) echo "error: option -$OPTARG is not implemented"; exit ;;
    esac
done

ARTIFACTS_DIR="artifacts"
# check dir exists
if [ ! -d  "$ARTIFACTS_DIR" ]; then
    echo "Creating artifacts directory $ARTIFACTS_DIR"
    mkdir -p $ARTIFACTS_DIR
fi

# echo shell commands when they are executed.
set -x

# Build Utils
echo "Building Utils ..."
mvn install -f $SCRIPTPATH/Utils/pom.xml -Dmaven.repo.local=$SCRIPTPATH/.repository -Dcheckstyle.skip=$SKIP_CHECKSTYLE $MAVEN_QUIET
mvn install -f $SCRIPTPATH/PluginsAndFeatures/AddLibrary/AzureLibraries/pom.xml -Dmaven.repo.local=$SCRIPTPATH/.repository $MAVEN_QUIET

# Build Eclipse plugin
if $BUILD_ECLIPSE; then
  echo "Building Eclipse plugin ..."
  mvn clean install -f $SCRIPTPATH/PluginsAndFeatures/azure-toolkit-for-eclipse/pom.xml $MAVEN_QUIET
  cp ./PluginsAndFeatures/azure-toolkit-for-eclipse/WindowsAzurePlugin4EJ/target/WindowsAzurePlugin4EJ*.zip ./$ARTIFACTS_DIR/WindowsAzurePlugin4EJ.zip
fi

# Build IntelliJ plugin
if $BUILD_INTELLIJ; then
  echo "Building IntelliJ plugin ..."
  chmod +x ./tools/IntellijVersionHelper
  ## Build intellij 2018.1 plugin
  if [ $INTELLIJ_VERSION == "true" ] ; then
      ./tools/IntellijVersionHelper 2018.1
  fi

  (cd PluginsAndFeatures/azure-toolkit-for-intellij && ./gradlew clean buildPlugin -s -Pintellij_version=IC-2018.1 -Pdep_plugins=org.intellij.scala:2018.1.8)

  cp ./PluginsAndFeatures/azure-toolkit-for-intellij/build/distributions/azure-toolkit-for-intellij.zip ./$ARTIFACTS_DIR/azure-toolkit-for-intellij-2018.1.zip

  ## Build intellij 2018.2 compatible plugin
  if [ $INTELLIJ_VERSION == "true" ] ; then
      ./tools/IntellijVersionHelper 2018.2
  fi

  (cd PluginsAndFeatures/azure-toolkit-for-intellij && ./gradlew clean buildPlugin -s)

  cp ./PluginsAndFeatures/azure-toolkit-for-intellij/build/distributions/azure-toolkit-for-intellij.zip ./$ARTIFACTS_DIR/azure-toolkit-for-intellij-2018.2.zip
fi

echo "ALL BUILD SUCCESSFUL"
