#!/bin/bash

set -e

SCRIPTPATH=$(pwd -P)
cd "$SCRIPTPATH"

MAVEN_QUIET=""
INTELLIJ_VERSION=false

while getopts ":hqv" option; do
    case $option in
        h) echo "usage: $0 [-h] [-q] [-v]"; exit ;;
        q) MAVEN_QUIET="-q" ;;
        v) INTELLIJ_VERSION=true ;;
        ?) echo "error: option -$OPTARG is not implemented"; exit ;;
    esac
done

ARTIFACTS_DIR="artifacts"
# check dir exists
if [ ! -d  "$ARTIFACTS_DIR" ]; then
    echo "Creating artifacts directory $ARTIFACTS_DIR"
    mkdir -p $ARTIFACTS_DIR
fi

# echo shell commands when they are executed.
set -x

# Build Utils
mvn install -f $SCRIPTPATH/Utils/pom.xml -Dmaven.repo.local=$SCRIPTPATH/.repository $MAVEN_QUIET
mvn install -f $SCRIPTPATH/PluginsAndFeatures/AddLibrary/AzureLibraries/pom.xml -Dmaven.repo.local=$SCRIPTPATH/.repository $MAVEN_QUIET

# # Build eclipse plugin
mvn clean install -f $SCRIPTPATH/PluginsAndFeatures/azure-toolkit-for-eclipse/pom.xml $MAVEN_QUIET
cp ./PluginsAndFeatures/azure-toolkit-for-eclipse/WindowsAzurePlugin4EJ/target/WindowsAzurePlugin4EJ*.zip ./$ARTIFACTS_DIR/WindowsAzurePlugin4EJ.zip

chmod +x ./gradlew
chmod +x ./tools/IntellijVersionHelper

# Build intellij 2017.3 plugin
if [ $INTELLIJ_VERSION == "true" ] ; then
    ./tools/IntellijVersionHelper 2017.3
fi
./gradlew clean buildPlugin --project-dir ./PluginsAndFeatures/azure-toolkit-for-intellij -s -Pintellij_version=IC-2017.3 -Pdep_plugins=org.intellij.scala:2017.3.15
cp ./PluginsAndFeatures/azure-toolkit-for-intellij/build/distributions/azure-toolkit-for-intellij.zip ./$ARTIFACTS_DIR/azure-toolkit-for-intellij-2017.3.zip

# Build intellij 2018.1 plugin
if [ $INTELLIJ_VERSION == "true" ] ; then
    ./tools/IntellijVersionHelper 2018.1
fi

./gradlew clean buildPlugin --project-dir ./PluginsAndFeatures/azure-toolkit-for-intellij -s 

cp ./PluginsAndFeatures/azure-toolkit-for-intellij/build/distributions/azure-toolkit-for-intellij.zip ./$ARTIFACTS_DIR/azure-toolkit-for-intellij-2018.1.zip

echo "ALL BUILD SUCCESSFUL"
