/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.hdinsight.sdk.rest.azure.serverless.spark.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for ResourcePoolState.
 */
public enum ResourcePoolState {
    /** Enum value New. */
    NEW("New"),

    /** Enum value Queued. */
    QUEUED("Queued"),

    /** Enum value Scheduling. */
    SCHEDULING("Scheduling"),

    /** Enum value Starting. */
    STARTING("Starting"),

    /** Enum value Launching. */
    LAUNCHING("Launching"),

    /** Enum value Running. */
    RUNNING("Running"),

    /** Enum value Rediscovering. */
    REDISCOVERING("Rediscovering"),

    /** Enum value Ending. */
    ENDING("Ending"),

    /** Enum value Ended. */
    ENDED("Ended");

    /** The actual serialized value for a ResourcePoolState instance. */
    private String value;

    ResourcePoolState(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ResourcePoolState instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ResourcePoolState object, or null if unable to parse.
     */
    @JsonCreator
    public static ResourcePoolState fromString(String value) {
        ResourcePoolState[] items = ResourcePoolState.values();
        for (ResourcePoolState item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
