/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.hdinsight.sdk.rest.azure.serverless.spark.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for SparkNodeType.
 */
public enum SparkNodeType {
    /** Enum value SparkMaster. */
    SPARK_MASTER("SparkMaster"),

    /** Enum value SparkWorker. */
    SPARK_WORKER("SparkWorker");

    /** The actual serialized value for a SparkNodeType instance. */
    private String value;

    SparkNodeType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a SparkNodeType instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed SparkNodeType object, or null if unable to parse.
     */
    @JsonCreator
    public static SparkNodeType fromString(String value) {
        SparkNodeType[] items = SparkNodeType.values();
        for (SparkNodeType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
