/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.hdinsight.sdk.rest.azure.serverless.spark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The parameters that can be used to update existing Data Lake Analytics spark
 * resource pool. Only update of number of spark workers is allowed.
 */
public class UpdateSparkResourcePool {
    /**
     * The spark resource pool specific properties.
     */
    @JsonProperty(value = "properties")
    private UpdateSparkResourcePoolParameters properties;

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public UpdateSparkResourcePoolParameters properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the UpdateSparkResourcePool object itself.
     */
    public UpdateSparkResourcePool withProperties(UpdateSparkResourcePoolParameters properties) {
        this.properties = properties;
        return this;
    }

}
