#!/bin/bash

set -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH

git checkout -- ../PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/plugin.xml
javac IntellijVersionHelper.java
java IntellijVersionHelper $1
